export const config = {
  camera: {
    position: { x: 0, y: 0, z: 4.2 },
    FOV: 30
  },
  threads: {
    instanceCount: 100,
    segments: 250,
    radiusSegments: 1,
    radius: 0.2
  },
  presets: {
    concentric: {
      paused: false,
      uColor1: '#fce197',
      uColor2: '#ffb3ef',
      uColorAmount: 1,
      uKernelSizeWorld: 0.66,
      uNoiseAmountWorld: 0,
      uInnerNoiseAmount: 1,
      uOuterNoiseAmount: 1,
      uPortalDepth: 0,
      uColorMix: 5,
      uNoiseSpeedWorld: 0.1,
      uConcentricRatio: 0,
      uNoiseSpeed: 0.01,
      uKernelSize: 0.3,
      uNoiseAmount: 0.5,
      uMoveDir: { x: 1, y: 0, z: 0 },
      uMoveAmount: 0,
      uPrevPosBlendAmount: 0.1,
      uGlobalSpinFreq: 0.1,
      uGlobalSpinAmp: 0,
      uMoveToStart: true
    },
    sweep: {
      paused: false,
      uColor1: '#fce197',
      uColor2: '#ffb3ef',
      uColorAmount: 1,
      uKernelSizeWorld: 0.3,
      uNoiseAmountWorld: 0.3,
      uInnerNoiseAmount: 1,
      uOuterNoiseAmount: 1,
      uPortalDepth: 1.25,
      uColorMix: 5,
      uNoiseSpeedWorld: 0.1,
      uConcentricRatio: 1,
      uNoiseSpeed: 0,
      uKernelSize: 0.48,
      uNoiseAmount: 0.5,
      uMoveDir: { x: 1, y: 0, z: 0 },
      uMoveAmount: 0.0019,
      uPrevPosBlendAmount: 0.08,
      uGlobalSpinFreq: 0.005,
      uGlobalSpinAmp: 0,
      uMoveToStart: false
    },
    radiate: {
      paused: false,
      uColor1: '#fce197',
      uColor2: '#ffb3ef',
      uColorAmount: 1,
      uKernelSizeWorld: 0.78,
      uNoiseAmountWorld: 0.3,
      uInnerNoiseAmount: 0.18999999999999995,
      uOuterNoiseAmount: 1,
      uPortalDepth: 0,
      uColorMix: 5,
      uNoiseSpeedWorld: 0.1,
      uConcentricRatio: 0.22,
      uNoiseSpeed: 0,
      uKernelSize: 0.48,
      uNoiseAmount: 0.5,
      uMoveDir: { x: 1, y: 0, z: 0 },
      uMoveAmount: 0.0019,
      uPrevPosBlendAmount: 0.08,
      uGlobalSpinFreq: 0.005,
      uGlobalSpinAmp: 0,
      uMoveToStart: true
    },
    zoom: {
      paused: false,
      uColor1: '#fce197',
      uColor2: '#ffb3ef',
      uColorAmount: 1,
      uKernelSizeWorld: 0.78,
      uNoiseAmountWorld: 0.3,
      uInnerNoiseAmount: 0,
      uOuterNoiseAmount: 1,
      uPortalDepth: 5,
      uColorMix: 0.5,
      uNoiseSpeedWorld: 0.1,
      uConcentricRatio: 0.3,
      uNoiseSpeed: 0,
      uKernelSize: 0.48,
      uNoiseAmount: 0.5,
      uMoveDir: { x: 1, y: 0, z: 0 },
      uMoveAmount: 0.0019,
      uPrevPosBlendAmount: 0.08,
      uGlobalSpinFreq: 0.005,
      uGlobalSpinAmp: 0,
      uMoveToStart: true
    },
    strands: {
      paused: false,
      uColor1: '#fce197',
      uColor2: '#ffb3ef',
      uColorAmount: 1,
      uKernelSizeWorld: 0.3,
      uNoiseAmountWorld: 0.3,
      uInnerNoiseAmount: 1,
      uOuterNoiseAmount: 1,
      uPortalDepth: 1.25,
      uColorMix: 5,
      uNoiseSpeedWorld: 0.1,
      uConcentricRatio: 1,
      uNoiseSpeed: 0,
      uKernelSize: 0.48,
      uNoiseAmount: 0.5,
      uMoveDir: { x: 1, y: 0, z: 0 },
      uMoveAmount: 0.0019,
      uPrevPosBlendAmount: 0.08,
      uGlobalSpinFreq: 0.005,
      uGlobalSpinAmp: 0.0006500000000000001,
      uMoveToStart: false
    }
  }
}
